spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: GOOGLE.API.OAUTH2.ID.KEY
            client-secret: GOOGLE.API.OAUTH2.SECRET.KEY
            scope: profile, email

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/blog
    username: sa
    password: hail

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace


